apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
  labels:
    app: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: localhost:32000/haproxy-with-config:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 8404
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-svc
  labels:
    app: haproxy
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
      protocol: TCP
      name: haproxy1
    - port: 8404
      targetPort: 8404
      nodePort: 31001
      protocol: TCP
      name: haproxy2
  selector:
    app: haproxy
