#!/bin/bash
EXPECTED=""
IMAGE_TO_INSPECT=intel/dlstreamer-pipeline-server:latest

docker pull $IMAGE_TO_INSPECT
OUTPUT=$(set -o pipefail; docker inspect $IMAGE_TO_INSPECT | grep -i proxy)
RETURN_CODE=$?
# Expect string to not exist
if [ $RETURN_CODE != 1 ]; then
    error
fi
if [[ "$OUTPUT" != "$EXPECTED" ]]; then
    error "Unexpected output"
fi
docker image rm $IMAGE_TO_INSPECT
