#!/bin/bash
EXPECTED=""

# Run client with bad option
OUTPUT=$(set -o pipefail; docker inspect dlstreamer-pipeline-server-gstreamer:latest | grep -i proxy)
RETURN_CODE=$?

# Expect to not match string
if [[ $RETURN_CODE != 1 ]]; then
    error
fi

if [[ ! "$OUTPUT" == "$EXPECTED" ]]; then
    error "Unexpected output"
fi
