#!/bin/bash

EXPECTED_RETVAL=0
EXPECTED="ERROR making EdgeX compose file!"

# Create mock command to interrupt normal flow
function teardown {
  unset make
}
trap teardown EXIT

function make() {
  echo "make being mocked by script_tests"
  return 1
}
export -f make

# Execute the negative test
OUTPUT=$($SOURCE_DIR/samples/edgex_bridge/fetch_edgex.sh)
RETURN_CODE=$?
if [[ $RETURN_CODE != $EXPECTED_RETVAL ]]; then
    error "Negative test got $RETURN_CODE instead of $EXPECTED_RETVAL"
fi
if [[ ! "$OUTPUT" == *"$EXPECTED"* ]]; then
    error "Test Case did not receive expected output!"
else
    echo "Negative test PASSED"
fi
