#!/bin/bash

NAME=vaserving
EXPECTED="Successfully fetched repo and produced compose file."

# Run script and check for successful complete
OUTPUT=$($SOURCE_DIR/samples/edgex_bridge/fetch_edgex.sh)
RETURN_CODE=$?

if [[ $RETURN_CODE != 0 ]]; then
    error
fi

if [[ ! "$OUTPUT" == *"$EXPECTED"* ]]; then
    error "Test Case did not receive expected output!"
fi
