#!/bin/bash
OUTPUT=
RETURN_CODE=

MODEL_NAMES=(mobilenet-ssd)
MODEL_NAMES+=(emotions-recognition-retail-0003)
MODEL_NAMES+=(landmarks-regression-retail-0009)
MODEL_NAMES+=(face-detection-retail-0004)

ALIAS_NAMES=(object_detection)
ALIAS_NAMES+=(emotion_recognition)
ALIAS_NAMES+=(landmarks_regression)
ALIAS_NAMES+=(face_detection_retail)

tmp_dir=$(mktemp -d -t model-downloader-XXXXXXXX)

error() {
    echo "======================="
    echo "Test Failed"
    echo "Return Code: $RETURN_CODE"
    echo "Detail: $1"
    echo "======================="
    echo "Output Begin"
    echo "======================="
    echo "$OUTPUT"
    echo "======================="
    echo "Output End"
    echo "======================="
    exit 1
}

check_directory() {
    model_path=$tmp_dir/models/$2/1
    if [ ! -d "$model_path" ]; then
	error "Missing Model Path: $model_path"
    fi
    model_proc=$model_path/$1.json
    if [ ! -f "$model_proc" ]; then
	error "Missing Model Proc: $model_proc"
    fi
    model_precision=$model_path/FP32
    if [ ! -d "$model_precision" ]; then
	error "Missing Model Precision: $model_precision"
    fi
    model_xml=$model_precision/$1.xml
    if [ ! -f "$model_xml" ]; then
	error "Missing Model XML: $model_xml"
    fi
    model_bin=$model_precision/$1.bin
    if [ ! -f "$model_bin" ]; then
	error "Missing Model BIN: $model_bin"
    fi
}

OUTPUT=$($SOURCE_DIR/tools/model_downloader/model_downloader.sh --model-list $SOURCE_DIR/models_list/models.list.yml --output $tmp_dir 2>&1)
RETURN_CODE=$?

if [[ $RETURN_CODE != 0 ]]; then
    rm -rf $tmp_dir
    error
fi

i=0
for model_name in ${MODEL_NAMES[@]}; do
    check_directory $model_name ${ALIAS_NAMES[$i]}
    i=$i+1	
done

rm -rf $tmp_dir
