#!/bin/bash

# Test for building container without models and pipelines
# Verifies correct build argument passed to docker build
# Does not verify end to end functionality

MODELS_COMMAND="--build-arg MODELS_COMMAND=do_not_copy_models "
PIPELINES_COMMAND="--build-arg PIPELINES_COMMAND=do_not_copy_pipelines "

OUTPUT=$($SOURCE_DIR/docker/build.sh --models NONE --pipelines NONE --dry-run 2>&1)
RETURN_CODE=$?

if [[ $RETURN_CODE != 0 ]]; then
    error
fi

if [[ ! "$OUTPUT" == *"$MODELS_COMMAND"* ]]; then
    error "Invalid MODELS_COMMAND build-arg"
fi

if [[ ! "$OUTPUT" == *"$PIPELINES_COMMAND"* ]]; then
    error "Invalid PIPELINES_COMMAND build-arg"
fi

