#!/bin/bash

if [ -e /dev/dri/renderD128 ]; then
    $SOURCE_DIR/docker/run.sh --gpu-device /dev/dri/renderD128 --non-interactive &
    sleep 5
    OUTPUT=$($SOURCE_DIR/client/pipeline_client.sh run object_detection/person_vehicle_bike https://github.com/intel-iot-devkit/sample-videos/blob/master/bottle-detection.mp4?raw=true --parameter detection-device GPU --parameter inference-interval 10)
    RETURN_CODE=$?

    # Stop server
    $SOURCE_DIR/tests/stop.sh

    if [[ $RETURN_CODE != 0 ]]; then
        error
    fi
fi
