#!/bin/bash

EXPECTED='Pipeline running'

# Run server and wait for init to complete
$SOURCE_DIR/docker/run.sh --non-interactive &
sleep 5

# Run client with int float and string parameters
OUTPUT=$($SOURCE_DIR/client/pipeline_client.sh run object_detection/person_vehicle_bike https://github.com/intel-iot-devkit/sample-videos/blob/master/classroom.mp4?raw=true --parameter inference-interval 2 --parameter threshold 0.5 --parameter detection-model-instance-id instance_id )
RETURN_CODE=$?

# Stop server
$SOURCE_DIR/tests/stop.sh

if [[ $RETURN_CODE != 0 ]]; then
    error
fi

if [[ ! "$OUTPUT" =~ .*"$EXPECTED".* ]]; then
  error "Unexpected output"
fi