#!/bin/bash

EXPECTED="Unable to connect to server, check if the pipeline-server microservice is running"

OUTPUT=$($SOURCE_DIR/client/pipeline_client.sh run object_detection/1 https://github.com/intel-iot-devkit/sample-videos/blob/master/bottle-detection.mp4?raw=true)
RETURN_CODE=$?

if [[ $RETURN_CODE != 1 ]]; then
    error
fi

if [[ ! "$OUTPUT" == *"$EXPECTED"* ]]; then
    error "Unexpected output"
fi
