#!/bin/bash

EXPECTED="Invalid Pipeline or Version"

# Run server and wait for init to complete
$SOURCE_DIR/docker/run.sh --non-interactive &
sleep 5

# Run client with bad option
OUTPUT=$($SOURCE_DIR/client/pipeline_client.sh run object_detection/123 https://github.com/intel-iot-devkit/sample-videos/blob/master/bottle-detection.mp4?raw=true)
RETURN_CODE=$?

# Stop server
$SOURCE_DIR/tests/stop.sh

if [[ $RETURN_CODE != 1 ]]; then
    error
fi

if [[ ! "$OUTPUT" == *"$EXPECTED"* ]]; then
    error "Unexpected output"
fi
