#!/bin/bash

ENTRYPOINT_ARGS="-c echo arg1 arg2"
EXPECTED="EntrypointArgs: '$ENTRYPOINT_ARGS '"

OUTPUT=$($SOURCE_DIR/docker/run.sh --entrypoint /bin/bash --entrypoint-args "$ENTRYPOINT_ARGS" --dry-run)
RETURN_CODE=$?

if [[ $RETURN_CODE != 0 ]]; then
    error "docker/run.sh has failed"
fi

if [[ ! "$OUTPUT" == *"$EXPECTED"* ]]; then
    error "Invalid Entrypoint Args"
fi
