#!/bin/bash

NAME=vaserving
EXPECTED="Invalid Pipeline or Version"

# Run server and wait for init to complete
$SOURCE_DIR/docker/run.sh --non-interactive --name $NAME -v /tmp:/tmp &
sleep 5

# Run client with bad option
OUTPUT=$($SOURCE_DIR/vaclient/vaclient.sh run object_detection/123 https://github.com/intel-iot-devkit/sample-videos/blob/master/bottle-detection.mp4?raw=true)
RETURN_CODE=$?

# Kill server
docker kill $NAME

if [[ $RETURN_CODE != 1 ]]; then
    error
fi

if [[ ! "$OUTPUT" == *"$EXPECTED"* ]]; then
    error "Unexpected output"
fi

