#!/bin/bash

EXPECTED=' - action_recognition/decoder
 - action_recognition/encoder
 - audio_detection/environment
 - emotion_recognition/1
 - face_detection_retail/1
 - object_classification/vehicle_attributes
 - object_detection/person
 - object_detection/person_vehicle_bike
 - object_detection/vehicle'

# Run server and wait for init to complete
$SOURCE_DIR/docker/run.sh --non-interactive &
sleep 5

# Run client with list-models
# tr is used to delete carriage return
OUTPUT=$($SOURCE_DIR/vaclient/vaclient.sh list-models | egrep '^ - ' | sort | tr -d "\r")
RETURN_CODE=$?

# Stop server
$SOURCE_DIR/tests/stop.sh

if [[ $RETURN_CODE != 0 ]]; then
    error
fi

if [[ ! "$OUTPUT" == "$EXPECTED" ]]; then
    error "Unexpected output"
fi