{{- if .Values.controlplane.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-for-hook
  namespace: "{{ .Release.Namespace }}"
subjects:
- kind: ServiceAccount
  name: service-account-for-hook
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: delete-pods-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-for-hook
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: delete-pods-role
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["*"]
  resources: ["pods", "configmaps", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
