apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mosquitto
  labels:
    app: mosquitto
spec:
  type: ClusterIP
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt-port
  selector:
    app: mosquitto