apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeline-server.fullname" . }}
  labels:
    {{- include "pipeline-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.webrtc }}
      targetPort: node-id
      protocol: TCP
      name: webrtc
  selector:
    {{- include "pipeline-server.selectorLabels" . | nindent 4 }}
