apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pipeline-server-cpu-worker
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-0300_8086.present
                operator: DoesNotExist
      containers:
        - name: pipeline-server