bases:
  - ../base
patches:
  - target:
      kind: DaemonSet
    patch: |-
      - op: replace
        path: /metadata/name
        value: pipeline-server-cpu-worker
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: pipeline-server-cpu-service
  - path: cpu-overlay.yaml